In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/Users/Vibhanshu/Desktop/MSc. Data Science/Python/Assignment/Sale_Customers.csv")
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [4]:
df.shape

(200, 5)

In [5]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [6]:
df.size

1000

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
CustomerID,200.0,100.50,57.879185,1.0,50.75,100.5,150.25,200.0
Age,200.0,38.85,13.969007,18.0,28.75,36.0,49.00,70.0
Annual Income (k$),200.0,60.56,26.264721,15.0,41.50,61.5,78.00,137.0
Spending Score (1-100),200.0,50.20,25.823522,1.0,34.75,50.0,73.00,99.0

In [8]:
print(df.to_string())

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
7             8  Female   23                  18                      94
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
13           14  Female   24                  20                      77
14           15    Male   37                  20                      13
15           16    Male   22                  20                      79
16           17  Female   35                  21                      35
17           18    Male   20                  21                      66
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
21           22    Male   25                  24                      73
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
25           26    Male   29                  28                      82
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
29           30  Female   23                  29                      87
30           31    Male   60                  30                       4
31           32  Female   21                  30                      73
32           33    Male   53                  33                       4
33           34    Male   18                  33                      92
34           35  Female   49                  33                      14
35           36  Female   21                  33                      81
36           37  Female   42                  34                      17
37           38  Female   30                  34                      73
38           39  Female   36                  37                      26
39           40  Female   20                  37                      75
40           41  Female   65                  38                      35
41           42    Male   24                  38                      92
42           43    Male   48                  39                      36
43           44  Female   31                  39                      61
44           45  Female   49                  39                      28
45           46  Female   24                  39                      65
46           47  Female   50                  40                      55
47           48  Female   27                  40                      47
48           49  Female   29                  40                      42
49           50  Female   31                  40                      42
50           51  Female   49                  42                      52
51           52    Male   33                  42                      60
52           53  Female   31                  43                      54
53           54    Male   59                  43                      60
54           55  Female   50                  43                      45
55           56    Male   47                  43                      41
56           57  Female   51                  44                      50
57           58    Male   69                  44                      46
58           59  Female   27                  46                      51
59           60    Male   53                  46                      46
60           61    Male   70                  46                      56
61           62    Male   19                  46                      55
62           63  Female   67                  47                      52
63           64  Female   54                  47                      59
64           65    Male   63                  48                      51
65           66    Male   18                  48                      59
66           67  Female   43                  48                      50
67           68  Female   68                  48                      48
68           69    Male   19                  48                      59
69           70  Female   32                  48                      47
70           71    Male   70                  49                      55
71           72  Female   47                  49                      42
72           73  Female   60                  50                      49
73           74  Female   60                  50                      56
74           75    Male   59                  54                      47
75           76    Male   26                  54                      54
76           77  Female   45                  54                      53
77           78    Male   40                  54                      48
78           79  Female   23                  54                      52
79           80  Female   49                  54                      42
80           81    Male   57                  54                      51
81           82    Male   38                  54                      55
82           83    Male   67                  54                      41
83           84  Female   46                  54                      44
84           85  Female   21                  54                      57
85           86    Male   48                  54                      46
86           87  Female   55                  57                      58
87           88  Female   22                  57                      55
88           89  Female   34                  58                      60
89           90  Female   50                  58                      46
90           91  Female   68                  59                      55
91           92    Male   18                  59                      41
92           93    Male   48                  60                      49
93           94  Female   40                  60                      40
94           95  Female   32                  60                      42
95           96    Male   24                  60                      52
96           97  Female   47                  60                      47
97           98  Female   27                  60                      50
98           99    Male   48                  61                      42
99          100    Male   20                  61                      49
100         101  Female   23                  62                      41
101         102  Female   49                  62                      48
102         103    Male   67                  62                      59
103         104    Male   26                  62                      55
104         105    Male   49                  62                      56
105         106  Female   21                  62                      42
106         107  Female   66                  63                      50
107         108    Male   54                  63                      46
108         109    Male   68                  63                      43
109         110    Male   66                  63                      48
110         111    Male   65                  63                      52
111         112  Female   19                  63                      54
112         113  Female   38                  64                      42
113         114    Male   19                  64                      46
114         115  Female   18                  65                      48
115         116  Female   19                  65                      50
116         117  Female   63                  65                      43
117         118  Female   49                  65                      59
118         119  Female   51                  67                      43
119         120  Female   50                  67                      57
120         121    Male   27                  67                      56
121         122  Female   38                  67                      40
122         123  Female   40                  69                      58
123         124    Male   39                  69                      91
124         125  Female   23                  70                      29
125         126  Female   31                  70                      77
126         127    Male   43                  71                      35
127         128    Male   40                  71                      95
128         129    Male   59                  71                      11
129         130    Male   38                  71                      75
130         131    Male   47                  71                       9
131         132    Male   39                  71                      75
132         133  Female   25                  72                      34
133         134  Female   31                  72                      71
134         135    Male   20                  73                       5
135         136  Female   29                  73                      88
136         137  Female   44                  73                       7
137         138    Male   32                  73                      73
138         139    Male   19                  74                      10
139         140  Female   35                  74                      72
140         141  Female   57                  75                       5
141         142    Male   32                  75                      93
142         143  Female   28                  76                      40
143         144  Female   32                  76                      87
144         145    Male   25                  77                      12
145         146    Male   28                  77                      97
146         147    Male   48                  77                      36
147         148  Female   32                  77                      74
148         149  Female   34                  78                      22
149         150    Male   34                  78                      90
150         151    Male   43                  78                      17
151         152    Male   39                  78                      88
152         153  Female   44                  78                      20
153         154  Female   38                  78                      76
154         155  Female   47                  78                      16
155         156  Female   27                  78                      89
156         157    Male   37                  78                       1
157         158  Female   30                  78                      78
158         159    Male   34                  78                       1
159         160  Female   30                  78                      73
160         161  Female   56                  79                      35
161         162  Female   29                  79                      83
162         163    Male   19                  81                       5
163         164  Female   31                  81                      93
164         165    Male   50                  85                      26
165         166  Female   36                  85                      75
166         167    Male   42                  86                      20
167         168  Female   33                  86                      95
168         169  Female   36                  87                      27
169         170    Male   32                  87                      63
170         171    Male   40                  87                      13
171         172    Male   28                  87                      75
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
175         176  Female   30                  88                      86
176         177    Male   58                  88                      15
177         178    Male   27                  88                      69
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
183         184  Female   29                  98                      88
184         185  Female   41                  99                      39
185         186    Male   30                  99                      97
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [9]:
#Data Cleaning
#Remove Rows
#Dropna method returns a new data frame and will not change the original.

new_df=df.dropna()

In [10]:
print(new_df.to_string())

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
7             8  Female   23                  18                      94
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
13           14  Female   24                  20                      77
14           15    Male   37                  20                      13
15           16    Male   22                  20                      79
16           17  Female   35                  21                      35
17           18    Male   20                  21                      66
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
21           22    Male   25                  24                      73
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
25           26    Male   29                  28                      82
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
29           30  Female   23                  29                      87
30           31    Male   60                  30                       4
31           32  Female   21                  30                      73
32           33    Male   53                  33                       4
33           34    Male   18                  33                      92
34           35  Female   49                  33                      14
35           36  Female   21                  33                      81
36           37  Female   42                  34                      17
37           38  Female   30                  34                      73
38           39  Female   36                  37                      26
39           40  Female   20                  37                      75
40           41  Female   65                  38                      35
41           42    Male   24                  38                      92
42           43    Male   48                  39                      36
43           44  Female   31                  39                      61
44           45  Female   49                  39                      28
45           46  Female   24                  39                      65
46           47  Female   50                  40                      55
47           48  Female   27                  40                      47
48           49  Female   29                  40                      42
49           50  Female   31                  40                      42
50           51  Female   49                  42                      52
51           52    Male   33                  42                      60
52           53  Female   31                  43                      54
53           54    Male   59                  43                      60
54           55  Female   50                  43                      45
55           56    Male   47                  43                      41
56           57  Female   51                  44                      50
57           58    Male   69                  44                      46
58           59  Female   27                  46                      51
59           60    Male   53                  46                      46
60           61    Male   70                  46                      56
61           62    Male   19                  46                      55
62           63  Female   67                  47                      52
63           64  Female   54                  47                      59
64           65    Male   63                  48                      51
65           66    Male   18                  48                      59
66           67  Female   43                  48                      50
67           68  Female   68                  48                      48
68           69    Male   19                  48                      59
69           70  Female   32                  48                      47
70           71    Male   70                  49                      55
71           72  Female   47                  49                      42
72           73  Female   60                  50                      49
73           74  Female   60                  50                      56
74           75    Male   59                  54                      47
75           76    Male   26                  54                      54
76           77  Female   45                  54                      53
77           78    Male   40                  54                      48
78           79  Female   23                  54                      52
79           80  Female   49                  54                      42
80           81    Male   57                  54                      51
81           82    Male   38                  54                      55
82           83    Male   67                  54                      41
83           84  Female   46                  54                      44
84           85  Female   21                  54                      57
85           86    Male   48                  54                      46
86           87  Female   55                  57                      58
87           88  Female   22                  57                      55
88           89  Female   34                  58                      60
89           90  Female   50                  58                      46
90           91  Female   68                  59                      55
91           92    Male   18                  59                      41
92           93    Male   48                  60                      49
93           94  Female   40                  60                      40
94           95  Female   32                  60                      42
95           96    Male   24                  60                      52
96           97  Female   47                  60                      47
97           98  Female   27                  60                      50
98           99    Male   48                  61                      42
99          100    Male   20                  61                      49
100         101  Female   23                  62                      41
101         102  Female   49                  62                      48
102         103    Male   67                  62                      59
103         104    Male   26                  62                      55
104         105    Male   49                  62                      56
105         106  Female   21                  62                      42
106         107  Female   66                  63                      50
107         108    Male   54                  63                      46
108         109    Male   68                  63                      43
109         110    Male   66                  63                      48
110         111    Male   65                  63                      52
111         112  Female   19                  63                      54
112         113  Female   38                  64                      42
113         114    Male   19                  64                      46
114         115  Female   18                  65                      48
115         116  Female   19                  65                      50
116         117  Female   63                  65                      43
117         118  Female   49                  65                      59
118         119  Female   51                  67                      43
119         120  Female   50                  67                      57
120         121    Male   27                  67                      56
121         122  Female   38                  67                      40
122         123  Female   40                  69                      58
123         124    Male   39                  69                      91
124         125  Female   23                  70                      29
125         126  Female   31                  70                      77
126         127    Male   43                  71                      35
127         128    Male   40                  71                      95
128         129    Male   59                  71                      11
129         130    Male   38                  71                      75
130         131    Male   47                  71                       9
131         132    Male   39                  71                      75
132         133  Female   25                  72                      34
133         134  Female   31                  72                      71
134         135    Male   20                  73                       5
135         136  Female   29                  73                      88
136         137  Female   44                  73                       7
137         138    Male   32                  73                      73
138         139    Male   19                  74                      10
139         140  Female   35                  74                      72
140         141  Female   57                  75                       5
141         142    Male   32                  75                      93
142         143  Female   28                  76                      40
143         144  Female   32                  76                      87
144         145    Male   25                  77                      12
145         146    Male   28                  77                      97
146         147    Male   48                  77                      36
147         148  Female   32                  77                      74
148         149  Female   34                  78                      22
149         150    Male   34                  78                      90
150         151    Male   43                  78                      17
151         152    Male   39                  78                      88
152         153  Female   44                  78                      20
153         154  Female   38                  78                      76
154         155  Female   47                  78                      16
155         156  Female   27                  78                      89
156         157    Male   37                  78                       1
157         158  Female   30                  78                      78
158         159    Male   34                  78                       1
159         160  Female   30                  78                      73
160         161  Female   56                  79                      35
161         162  Female   29                  79                      83
162         163    Male   19                  81                       5
163         164  Female   31                  81                      93
164         165    Male   50                  85                      26
165         166  Female   36                  85                      75
166         167    Male   42                  86                      20
167         168  Female   33                  86                      95
168         169  Female   36                  87                      27
169         170    Male   32                  87                      63
170         171    Male   40                  87                      13
171         172    Male   28                  87                      75
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
175         176  Female   30                  88                      86
176         177    Male   58                  88                      15
177         178    Male   27                  88                      69
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
183         184  Female   29                  98                      88
184         185  Female   41                  99                      39
185         186    Male   30                  99                      97
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [11]:
new_df.shape

(200, 5)

In [12]:
new_df.size

1000

In [13]:
#Dropna(inplace=True) will not return a new dataframe but it will remove all rows containing null value from the original dataframe.
df.dropna(inplace=True)
print(df.to_string())

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
7             8  Female   23                  18                      94
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
13           14  Female   24                  20                      77
14           15    Male   37                  20                      13
15           16    Male   22                  20                      79
16           17  Female   35                  21                      35
17           18    Male   20                  21                      66
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
21           22    Male   25                  24                      73
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
25           26    Male   29                  28                      82
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
29           30  Female   23                  29                      87
30           31    Male   60                  30                       4
31           32  Female   21                  30                      73
32           33    Male   53                  33                       4
33           34    Male   18                  33                      92
34           35  Female   49                  33                      14
35           36  Female   21                  33                      81
36           37  Female   42                  34                      17
37           38  Female   30                  34                      73
38           39  Female   36                  37                      26
39           40  Female   20                  37                      75
40           41  Female   65                  38                      35
41           42    Male   24                  38                      92
42           43    Male   48                  39                      36
43           44  Female   31                  39                      61
44           45  Female   49                  39                      28
45           46  Female   24                  39                      65
46           47  Female   50                  40                      55
47           48  Female   27                  40                      47
48           49  Female   29                  40                      42
49           50  Female   31                  40                      42
50           51  Female   49                  42                      52
51           52    Male   33                  42                      60
52           53  Female   31                  43                      54
53           54    Male   59                  43                      60
54           55  Female   50                  43                      45
55           56    Male   47                  43                      41
56           57  Female   51                  44                      50
57           58    Male   69                  44                      46
58           59  Female   27                  46                      51
59           60    Male   53                  46                      46
60           61    Male   70                  46                      56
61           62    Male   19                  46                      55
62           63  Female   67                  47                      52
63           64  Female   54                  47                      59
64           65    Male   63                  48                      51
65           66    Male   18                  48                      59
66           67  Female   43                  48                      50
67           68  Female   68                  48                      48
68           69    Male   19                  48                      59
69           70  Female   32                  48                      47
70           71    Male   70                  49                      55
71           72  Female   47                  49                      42
72           73  Female   60                  50                      49
73           74  Female   60                  50                      56
74           75    Male   59                  54                      47
75           76    Male   26                  54                      54
76           77  Female   45                  54                      53
77           78    Male   40                  54                      48
78           79  Female   23                  54                      52
79           80  Female   49                  54                      42
80           81    Male   57                  54                      51
81           82    Male   38                  54                      55
82           83    Male   67                  54                      41
83           84  Female   46                  54                      44
84           85  Female   21                  54                      57
85           86    Male   48                  54                      46
86           87  Female   55                  57                      58
87           88  Female   22                  57                      55
88           89  Female   34                  58                      60
89           90  Female   50                  58                      46
90           91  Female   68                  59                      55
91           92    Male   18                  59                      41
92           93    Male   48                  60                      49
93           94  Female   40                  60                      40
94           95  Female   32                  60                      42
95           96    Male   24                  60                      52
96           97  Female   47                  60                      47
97           98  Female   27                  60                      50
98           99    Male   48                  61                      42
99          100    Male   20                  61                      49
100         101  Female   23                  62                      41
101         102  Female   49                  62                      48
102         103    Male   67                  62                      59
103         104    Male   26                  62                      55
104         105    Male   49                  62                      56
105         106  Female   21                  62                      42
106         107  Female   66                  63                      50
107         108    Male   54                  63                      46
108         109    Male   68                  63                      43
109         110    Male   66                  63                      48
110         111    Male   65                  63                      52
111         112  Female   19                  63                      54
112         113  Female   38                  64                      42
113         114    Male   19                  64                      46
114         115  Female   18                  65                      48
115         116  Female   19                  65                      50
116         117  Female   63                  65                      43
117         118  Female   49                  65                      59
118         119  Female   51                  67                      43
119         120  Female   50                  67                      57
120         121    Male   27                  67                      56
121         122  Female   38                  67                      40
122         123  Female   40                  69                      58
123         124    Male   39                  69                      91
124         125  Female   23                  70                      29
125         126  Female   31                  70                      77
126         127    Male   43                  71                      35
127         128    Male   40                  71                      95
128         129    Male   59                  71                      11
129         130    Male   38                  71                      75
130         131    Male   47                  71                       9
131         132    Male   39                  71                      75
132         133  Female   25                  72                      34
133         134  Female   31                  72                      71
134         135    Male   20                  73                       5
135         136  Female   29                  73                      88
136         137  Female   44                  73                       7
137         138    Male   32                  73                      73
138         139    Male   19                  74                      10
139         140  Female   35                  74                      72
140         141  Female   57                  75                       5
141         142    Male   32                  75                      93
142         143  Female   28                  76                      40
143         144  Female   32                  76                      87
144         145    Male   25                  77                      12
145         146    Male   28                  77                      97
146         147    Male   48                  77                      36
147         148  Female   32                  77                      74
148         149  Female   34                  78                      22
149         150    Male   34                  78                      90
150         151    Male   43                  78                      17
151         152    Male   39                  78                      88
152         153  Female   44                  78                      20
153         154  Female   38                  78                      76
154         155  Female   47                  78                      16
155         156  Female   27                  78                      89
156         157    Male   37                  78                       1
157         158  Female   30                  78                      78
158         159    Male   34                  78                       1
159         160  Female   30                  78                      73
160         161  Female   56                  79                      35
161         162  Female   29                  79                      83
162         163    Male   19                  81                       5
163         164  Female   31                  81                      93
164         165    Male   50                  85                      26
165         166  Female   36                  85                      75
166         167    Male   42                  86                      20
167         168  Female   33                  86                      95
168         169  Female   36                  87                      27
169         170    Male   32                  87                      63
170         171    Male   40                  87                      13
171         172    Male   28                  87                      75
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
175         176  Female   30                  88                      86
176         177    Male   58                  88                      15
177         178    Male   27                  88                      69
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
183         184  Female   29                  98                      88
184         185  Female   41                  99                      39
185         186    Male   30                  99                      97
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [14]:
#Replace Empty Values.
df=pd.read_csv("/Users/Vibhanshu/Desktop/MSc. Data Science/Python/Assignment/Sale_Customers.csv")

In [15]:
df.fillna(999,inplace=True)
print(df.to_string())

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
7             8  Female   23                  18                      94
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
13           14  Female   24                  20                      77
14           15    Male   37                  20                      13
15           16    Male   22                  20                      79
16           17  Female   35                  21                      35
17           18    Male   20                  21                      66
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
21           22    Male   25                  24                      73
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
25           26    Male   29                  28                      82
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
29           30  Female   23                  29                      87
30           31    Male   60                  30                       4
31           32  Female   21                  30                      73
32           33    Male   53                  33                       4
33           34    Male   18                  33                      92
34           35  Female   49                  33                      14
35           36  Female   21                  33                      81
36           37  Female   42                  34                      17
37           38  Female   30                  34                      73
38           39  Female   36                  37                      26
39           40  Female   20                  37                      75
40           41  Female   65                  38                      35
41           42    Male   24                  38                      92
42           43    Male   48                  39                      36
43           44  Female   31                  39                      61
44           45  Female   49                  39                      28
45           46  Female   24                  39                      65
46           47  Female   50                  40                      55
47           48  Female   27                  40                      47
48           49  Female   29                  40                      42
49           50  Female   31                  40                      42
50           51  Female   49                  42                      52
51           52    Male   33                  42                      60
52           53  Female   31                  43                      54
53           54    Male   59                  43                      60
54           55  Female   50                  43                      45
55           56    Male   47                  43                      41
56           57  Female   51                  44                      50
57           58    Male   69                  44                      46
58           59  Female   27                  46                      51
59           60    Male   53                  46                      46
60           61    Male   70                  46                      56
61           62    Male   19                  46                      55
62           63  Female   67                  47                      52
63           64  Female   54                  47                      59
64           65    Male   63                  48                      51
65           66    Male   18                  48                      59
66           67  Female   43                  48                      50
67           68  Female   68                  48                      48
68           69    Male   19                  48                      59
69           70  Female   32                  48                      47
70           71    Male   70                  49                      55
71           72  Female   47                  49                      42
72           73  Female   60                  50                      49
73           74  Female   60                  50                      56
74           75    Male   59                  54                      47
75           76    Male   26                  54                      54
76           77  Female   45                  54                      53
77           78    Male   40                  54                      48
78           79  Female   23                  54                      52
79           80  Female   49                  54                      42
80           81    Male   57                  54                      51
81           82    Male   38                  54                      55
82           83    Male   67                  54                      41
83           84  Female   46                  54                      44
84           85  Female   21                  54                      57
85           86    Male   48                  54                      46
86           87  Female   55                  57                      58
87           88  Female   22                  57                      55
88           89  Female   34                  58                      60
89           90  Female   50                  58                      46
90           91  Female   68                  59                      55
91           92    Male   18                  59                      41
92           93    Male   48                  60                      49
93           94  Female   40                  60                      40
94           95  Female   32                  60                      42
95           96    Male   24                  60                      52
96           97  Female   47                  60                      47
97           98  Female   27                  60                      50
98           99    Male   48                  61                      42
99          100    Male   20                  61                      49
100         101  Female   23                  62                      41
101         102  Female   49                  62                      48
102         103    Male   67                  62                      59
103         104    Male   26                  62                      55
104         105    Male   49                  62                      56
105         106  Female   21                  62                      42
106         107  Female   66                  63                      50
107         108    Male   54                  63                      46
108         109    Male   68                  63                      43
109         110    Male   66                  63                      48
110         111    Male   65                  63                      52
111         112  Female   19                  63                      54
112         113  Female   38                  64                      42
113         114    Male   19                  64                      46
114         115  Female   18                  65                      48
115         116  Female   19                  65                      50
116         117  Female   63                  65                      43
117         118  Female   49                  65                      59
118         119  Female   51                  67                      43
119         120  Female   50                  67                      57
120         121    Male   27                  67                      56
121         122  Female   38                  67                      40
122         123  Female   40                  69                      58
123         124    Male   39                  69                      91
124         125  Female   23                  70                      29
125         126  Female   31                  70                      77
126         127    Male   43                  71                      35
127         128    Male   40                  71                      95
128         129    Male   59                  71                      11
129         130    Male   38                  71                      75
130         131    Male   47                  71                       9
131         132    Male   39                  71                      75
132         133  Female   25                  72                      34
133         134  Female   31                  72                      71
134         135    Male   20                  73                       5
135         136  Female   29                  73                      88
136         137  Female   44                  73                       7
137         138    Male   32                  73                      73
138         139    Male   19                  74                      10
139         140  Female   35                  74                      72
140         141  Female   57                  75                       5
141         142    Male   32                  75                      93
142         143  Female   28                  76                      40
143         144  Female   32                  76                      87
144         145    Male   25                  77                      12
145         146    Male   28                  77                      97
146         147    Male   48                  77                      36
147         148  Female   32                  77                      74
148         149  Female   34                  78                      22
149         150    Male   34                  78                      90
150         151    Male   43                  78                      17
151         152    Male   39                  78                      88
152         153  Female   44                  78                      20
153         154  Female   38                  78                      76
154         155  Female   47                  78                      16
155         156  Female   27                  78                      89
156         157    Male   37                  78                       1
157         158  Female   30                  78                      78
158         159    Male   34                  78                       1
159         160  Female   30                  78                      73
160         161  Female   56                  79                      35
161         162  Female   29                  79                      83
162         163    Male   19                  81                       5
163         164  Female   31                  81                      93
164         165    Male   50                  85                      26
165         166  Female   36                  85                      75
166         167    Male   42                  86                      20
167         168  Female   33                  86                      95
168         169  Female   36                  87                      27
169         170    Male   32                  87                      63
170         171    Male   40                  87                      13
171         172    Male   28                  87                      75
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
175         176  Female   30                  88                      86
176         177    Male   58                  88                      15
177         178    Male   27                  88                      69
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
183         184  Female   29                  98                      88
184         185  Female   41                  99                      39
185         186    Male   30                  99                      97
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [16]:
df=pd.read_csv("/Users/Vibhanshu/Desktop/MSc. Data Science/Python/Assignment/Sale_Customers.csv")

In [18]:
df["Annual Income (k$)"].fillna(777,inplace=True)
print(df.to_string())

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
7             8  Female   23                  18                      94
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
13           14  Female   24                  20                      77
14           15    Male   37                  20                      13
15           16    Male   22                  20                      79
16           17  Female   35                  21                      35
17           18    Male   20                  21                      66
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
21           22    Male   25                  24                      73
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
25           26    Male   29                  28                      82
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
29           30  Female   23                  29                      87
30           31    Male   60                  30                       4
31           32  Female   21                  30                      73
32           33    Male   53                  33                       4
33           34    Male   18                  33                      92
34           35  Female   49                  33                      14
35           36  Female   21                  33                      81
36           37  Female   42                  34                      17
37           38  Female   30                  34                      73
38           39  Female   36                  37                      26
39           40  Female   20                  37                      75
40           41  Female   65                  38                      35
41           42    Male   24                  38                      92
42           43    Male   48                  39                      36
43           44  Female   31                  39                      61
44           45  Female   49                  39                      28
45           46  Female   24                  39                      65
46           47  Female   50                  40                      55
47           48  Female   27                  40                      47
48           49  Female   29                  40                      42
49           50  Female   31                  40                      42
50           51  Female   49                  42                      52
51           52    Male   33                  42                      60
52           53  Female   31                  43                      54
53           54    Male   59                  43                      60
54           55  Female   50                  43                      45
55           56    Male   47                  43                      41
56           57  Female   51                  44                      50
57           58    Male   69                  44                      46
58           59  Female   27                  46                      51
59           60    Male   53                  46                      46
60           61    Male   70                  46                      56
61           62    Male   19                  46                      55
62           63  Female   67                  47                      52
63           64  Female   54                  47                      59
64           65    Male   63                  48                      51
65           66    Male   18                  48                      59
66           67  Female   43                  48                      50
67           68  Female   68                  48                      48
68           69    Male   19                  48                      59
69           70  Female   32                  48                      47
70           71    Male   70                  49                      55
71           72  Female   47                  49                      42
72           73  Female   60                  50                      49
73           74  Female   60                  50                      56
74           75    Male   59                  54                      47
75           76    Male   26                  54                      54
76           77  Female   45                  54                      53
77           78    Male   40                  54                      48
78           79  Female   23                  54                      52
79           80  Female   49                  54                      42
80           81    Male   57                  54                      51
81           82    Male   38                  54                      55
82           83    Male   67                  54                      41
83           84  Female   46                  54                      44
84           85  Female   21                  54                      57
85           86    Male   48                  54                      46
86           87  Female   55                  57                      58
87           88  Female   22                  57                      55
88           89  Female   34                  58                      60
89           90  Female   50                  58                      46
90           91  Female   68                  59                      55
91           92    Male   18                  59                      41
92           93    Male   48                  60                      49
93           94  Female   40                  60                      40
94           95  Female   32                  60                      42
95           96    Male   24                  60                      52
96           97  Female   47                  60                      47
97           98  Female   27                  60                      50
98           99    Male   48                  61                      42
99          100    Male   20                  61                      49
100         101  Female   23                  62                      41
101         102  Female   49                  62                      48
102         103    Male   67                  62                      59
103         104    Male   26                  62                      55
104         105    Male   49                  62                      56
105         106  Female   21                  62                      42
106         107  Female   66                  63                      50
107         108    Male   54                  63                      46
108         109    Male   68                  63                      43
109         110    Male   66                  63                      48
110         111    Male   65                  63                      52
111         112  Female   19                  63                      54
112         113  Female   38                  64                      42
113         114    Male   19                  64                      46
114         115  Female   18                  65                      48
115         116  Female   19                  65                      50
116         117  Female   63                  65                      43
117         118  Female   49                  65                      59
118         119  Female   51                  67                      43
119         120  Female   50                  67                      57
120         121    Male   27                  67                      56
121         122  Female   38                  67                      40
122         123  Female   40                  69                      58
123         124    Male   39                  69                      91
124         125  Female   23                  70                      29
125         126  Female   31                  70                      77
126         127    Male   43                  71                      35
127         128    Male   40                  71                      95
128         129    Male   59                  71                      11
129         130    Male   38                  71                      75
130         131    Male   47                  71                       9
131         132    Male   39                  71                      75
132         133  Female   25                  72                      34
133         134  Female   31                  72                      71
134         135    Male   20                  73                       5
135         136  Female   29                  73                      88
136         137  Female   44                  73                       7
137         138    Male   32                  73                      73
138         139    Male   19                  74                      10
139         140  Female   35                  74                      72
140         141  Female   57                  75                       5
141         142    Male   32                  75                      93
142         143  Female   28                  76                      40
143         144  Female   32                  76                      87
144         145    Male   25                  77                      12
145         146    Male   28                  77                      97
146         147    Male   48                  77                      36
147         148  Female   32                  77                      74
148         149  Female   34                  78                      22
149         150    Male   34                  78                      90
150         151    Male   43                  78                      17
151         152    Male   39                  78                      88
152         153  Female   44                  78                      20
153         154  Female   38                  78                      76
154         155  Female   47                  78                      16
155         156  Female   27                  78                      89
156         157    Male   37                  78                       1
157         158  Female   30                  78                      78
158         159    Male   34                  78                       1
159         160  Female   30                  78                      73
160         161  Female   56                  79                      35
161         162  Female   29                  79                      83
162         163    Male   19                  81                       5
163         164  Female   31                  81                      93
164         165    Male   50                  85                      26
165         166  Female   36                  85                      75
166         167    Male   42                  86                      20
167         168  Female   33                  86                      95
168         169  Female   36                  87                      27
169         170    Male   32                  87                      63
170         171    Male   40                  87                      13
171         172    Male   28                  87                      75
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
175         176  Female   30                  88                      86
176         177    Male   58                  88                      15
177         178    Male   27                  88                      69
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
183         184  Female   29                  98                      88
184         185  Female   41                  99                      39
185         186    Male   30                  99                      97
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [19]:
#Replace using mean, median or mod.
#Mean
df=pd.read_csv("/Users/Vibhanshu/Desktop/MSc. Data Science/Python/Assignment/Sale_Customers.csv")
x=df["Annual Income (k$)"].mean()
df["Annual Income (k$)"].fillna(x,inplace=True)
print(df.to_string())

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
7             8  Female   23                  18                      94
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
13           14  Female   24                  20                      77
14           15    Male   37                  20                      13
15           16    Male   22                  20                      79
16           17  Female   35                  21                      35
17           18    Male   20                  21                      66
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
21           22    Male   25                  24                      73
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
25           26    Male   29                  28                      82
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
29           30  Female   23                  29                      87
30           31    Male   60                  30                       4
31           32  Female   21                  30                      73
32           33    Male   53                  33                       4
33           34    Male   18                  33                      92
34           35  Female   49                  33                      14
35           36  Female   21                  33                      81
36           37  Female   42                  34                      17
37           38  Female   30                  34                      73
38           39  Female   36                  37                      26
39           40  Female   20                  37                      75
40           41  Female   65                  38                      35
41           42    Male   24                  38                      92
42           43    Male   48                  39                      36
43           44  Female   31                  39                      61
44           45  Female   49                  39                      28
45           46  Female   24                  39                      65
46           47  Female   50                  40                      55
47           48  Female   27                  40                      47
48           49  Female   29                  40                      42
49           50  Female   31                  40                      42
50           51  Female   49                  42                      52
51           52    Male   33                  42                      60
52           53  Female   31                  43                      54
53           54    Male   59                  43                      60
54           55  Female   50                  43                      45
55           56    Male   47                  43                      41
56           57  Female   51                  44                      50
57           58    Male   69                  44                      46
58           59  Female   27                  46                      51
59           60    Male   53                  46                      46
60           61    Male   70                  46                      56
61           62    Male   19                  46                      55
62           63  Female   67                  47                      52
63           64  Female   54                  47                      59
64           65    Male   63                  48                      51
65           66    Male   18                  48                      59
66           67  Female   43                  48                      50
67           68  Female   68                  48                      48
68           69    Male   19                  48                      59
69           70  Female   32                  48                      47
70           71    Male   70                  49                      55
71           72  Female   47                  49                      42
72           73  Female   60                  50                      49
73           74  Female   60                  50                      56
74           75    Male   59                  54                      47
75           76    Male   26                  54                      54
76           77  Female   45                  54                      53
77           78    Male   40                  54                      48
78           79  Female   23                  54                      52
79           80  Female   49                  54                      42
80           81    Male   57                  54                      51
81           82    Male   38                  54                      55
82           83    Male   67                  54                      41
83           84  Female   46                  54                      44
84           85  Female   21                  54                      57
85           86    Male   48                  54                      46
86           87  Female   55                  57                      58
87           88  Female   22                  57                      55
88           89  Female   34                  58                      60
89           90  Female   50                  58                      46
90           91  Female   68                  59                      55
91           92    Male   18                  59                      41
92           93    Male   48                  60                      49
93           94  Female   40                  60                      40
94           95  Female   32                  60                      42
95           96    Male   24                  60                      52
96           97  Female   47                  60                      47
97           98  Female   27                  60                      50
98           99    Male   48                  61                      42
99          100    Male   20                  61                      49
100         101  Female   23                  62                      41
101         102  Female   49                  62                      48
102         103    Male   67                  62                      59
103         104    Male   26                  62                      55
104         105    Male   49                  62                      56
105         106  Female   21                  62                      42
106         107  Female   66                  63                      50
107         108    Male   54                  63                      46
108         109    Male   68                  63                      43
109         110    Male   66                  63                      48
110         111    Male   65                  63                      52
111         112  Female   19                  63                      54
112         113  Female   38                  64                      42
113         114    Male   19                  64                      46
114         115  Female   18                  65                      48
115         116  Female   19                  65                      50
116         117  Female   63                  65                      43
117         118  Female   49                  65                      59
118         119  Female   51                  67                      43
119         120  Female   50                  67                      57
120         121    Male   27                  67                      56
121         122  Female   38                  67                      40
122         123  Female   40                  69                      58
123         124    Male   39                  69                      91
124         125  Female   23                  70                      29
125         126  Female   31                  70                      77
126         127    Male   43                  71                      35
127         128    Male   40                  71                      95
128         129    Male   59                  71                      11
129         130    Male   38                  71                      75
130         131    Male   47                  71                       9
131         132    Male   39                  71                      75
132         133  Female   25                  72                      34
133         134  Female   31                  72                      71
134         135    Male   20                  73                       5
135         136  Female   29                  73                      88
136         137  Female   44                  73                       7
137         138    Male   32                  73                      73
138         139    Male   19                  74                      10
139         140  Female   35                  74                      72
140         141  Female   57                  75                       5
141         142    Male   32                  75                      93
142         143  Female   28                  76                      40
143         144  Female   32                  76                      87
144         145    Male   25                  77                      12
145         146    Male   28                  77                      97
146         147    Male   48                  77                      36
147         148  Female   32                  77                      74
148         149  Female   34                  78                      22
149         150    Male   34                  78                      90
150         151    Male   43                  78                      17
151         152    Male   39                  78                      88
152         153  Female   44                  78                      20
153         154  Female   38                  78                      76
154         155  Female   47                  78                      16
155         156  Female   27                  78                      89
156         157    Male   37                  78                       1
157         158  Female   30                  78                      78
158         159    Male   34                  78                       1
159         160  Female   30                  78                      73
160         161  Female   56                  79                      35
161         162  Female   29                  79                      83
162         163    Male   19                  81                       5
163         164  Female   31                  81                      93
164         165    Male   50                  85                      26
165         166  Female   36                  85                      75
166         167    Male   42                  86                      20
167         168  Female   33                  86                      95
168         169  Female   36                  87                      27
169         170    Male   32                  87                      63
170         171    Male   40                  87                      13
171         172    Male   28                  87                      75
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
175         176  Female   30                  88                      86
176         177    Male   58                  88                      15
177         178    Male   27                  88                      69
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
183         184  Female   29                  98                      88
184         185  Female   41                  99                      39
185         186    Male   30                  99                      97
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [20]:
#Replace using mean, median or mode.
#Median
df=pd.read_csv("/Users/Vibhanshu/Desktop/MSc. Data Science/Python/Assignment/Sale_Customers.csv")
x=df["Annual Income (k$)"].median()
df["Annual Income (k$)"].fillna(x,inplace=True)
print(df.to_string())

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
7             8  Female   23                  18                      94
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
13           14  Female   24                  20                      77
14           15    Male   37                  20                      13
15           16    Male   22                  20                      79
16           17  Female   35                  21                      35
17           18    Male   20                  21                      66
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
21           22    Male   25                  24                      73
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
25           26    Male   29                  28                      82
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
29           30  Female   23                  29                      87
30           31    Male   60                  30                       4
31           32  Female   21                  30                      73
32           33    Male   53                  33                       4
33           34    Male   18                  33                      92
34           35  Female   49                  33                      14
35           36  Female   21                  33                      81
36           37  Female   42                  34                      17
37           38  Female   30                  34                      73
38           39  Female   36                  37                      26
39           40  Female   20                  37                      75
40           41  Female   65                  38                      35
41           42    Male   24                  38                      92
42           43    Male   48                  39                      36
43           44  Female   31                  39                      61
44           45  Female   49                  39                      28
45           46  Female   24                  39                      65
46           47  Female   50                  40                      55
47           48  Female   27                  40                      47
48           49  Female   29                  40                      42
49           50  Female   31                  40                      42
50           51  Female   49                  42                      52
51           52    Male   33                  42                      60
52           53  Female   31                  43                      54
53           54    Male   59                  43                      60
54           55  Female   50                  43                      45
55           56    Male   47                  43                      41
56           57  Female   51                  44                      50
57           58    Male   69                  44                      46
58           59  Female   27                  46                      51
59           60    Male   53                  46                      46
60           61    Male   70                  46                      56
61           62    Male   19                  46                      55
62           63  Female   67                  47                      52
63           64  Female   54                  47                      59
64           65    Male   63                  48                      51
65           66    Male   18                  48                      59
66           67  Female   43                  48                      50
67           68  Female   68                  48                      48
68           69    Male   19                  48                      59
69           70  Female   32                  48                      47
70           71    Male   70                  49                      55
71           72  Female   47                  49                      42
72           73  Female   60                  50                      49
73           74  Female   60                  50                      56
74           75    Male   59                  54                      47
75           76    Male   26                  54                      54
76           77  Female   45                  54                      53
77           78    Male   40                  54                      48
78           79  Female   23                  54                      52
79           80  Female   49                  54                      42
80           81    Male   57                  54                      51
81           82    Male   38                  54                      55
82           83    Male   67                  54                      41
83           84  Female   46                  54                      44
84           85  Female   21                  54                      57
85           86    Male   48                  54                      46
86           87  Female   55                  57                      58
87           88  Female   22                  57                      55
88           89  Female   34                  58                      60
89           90  Female   50                  58                      46
90           91  Female   68                  59                      55
91           92    Male   18                  59                      41
92           93    Male   48                  60                      49
93           94  Female   40                  60                      40
94           95  Female   32                  60                      42
95           96    Male   24                  60                      52
96           97  Female   47                  60                      47
97           98  Female   27                  60                      50
98           99    Male   48                  61                      42
99          100    Male   20                  61                      49
100         101  Female   23                  62                      41
101         102  Female   49                  62                      48
102         103    Male   67                  62                      59
103         104    Male   26                  62                      55
104         105    Male   49                  62                      56
105         106  Female   21                  62                      42
106         107  Female   66                  63                      50
107         108    Male   54                  63                      46
108         109    Male   68                  63                      43
109         110    Male   66                  63                      48
110         111    Male   65                  63                      52
111         112  Female   19                  63                      54
112         113  Female   38                  64                      42
113         114    Male   19                  64                      46
114         115  Female   18                  65                      48
115         116  Female   19                  65                      50
116         117  Female   63                  65                      43
117         118  Female   49                  65                      59
118         119  Female   51                  67                      43
119         120  Female   50                  67                      57
120         121    Male   27                  67                      56
121         122  Female   38                  67                      40
122         123  Female   40                  69                      58
123         124    Male   39                  69                      91
124         125  Female   23                  70                      29
125         126  Female   31                  70                      77
126         127    Male   43                  71                      35
127         128    Male   40                  71                      95
128         129    Male   59                  71                      11
129         130    Male   38                  71                      75
130         131    Male   47                  71                       9
131         132    Male   39                  71                      75
132         133  Female   25                  72                      34
133         134  Female   31                  72                      71
134         135    Male   20                  73                       5
135         136  Female   29                  73                      88
136         137  Female   44                  73                       7
137         138    Male   32                  73                      73
138         139    Male   19                  74                      10
139         140  Female   35                  74                      72
140         141  Female   57                  75                       5
141         142    Male   32                  75                      93
142         143  Female   28                  76                      40
143         144  Female   32                  76                      87
144         145    Male   25                  77                      12
145         146    Male   28                  77                      97
146         147    Male   48                  77                      36
147         148  Female   32                  77                      74
148         149  Female   34                  78                      22
149         150    Male   34                  78                      90
150         151    Male   43                  78                      17
151         152    Male   39                  78                      88
152         153  Female   44                  78                      20
153         154  Female   38                  78                      76
154         155  Female   47                  78                      16
155         156  Female   27                  78                      89
156         157    Male   37                  78                       1
157         158  Female   30                  78                      78
158         159    Male   34                  78                       1
159         160  Female   30                  78                      73
160         161  Female   56                  79                      35
161         162  Female   29                  79                      83
162         163    Male   19                  81                       5
163         164  Female   31                  81                      93
164         165    Male   50                  85                      26
165         166  Female   36                  85                      75
166         167    Male   42                  86                      20
167         168  Female   33                  86                      95
168         169  Female   36                  87                      27
169         170    Male   32                  87                      63
170         171    Male   40                  87                      13
171         172    Male   28                  87                      75
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
175         176  Female   30                  88                      86
176         177    Male   58                  88                      15
177         178    Male   27                  88                      69
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
183         184  Female   29                  98                      88
184         185  Female   41                  99                      39
185         186    Male   30                  99                      97
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [21]:
#Mode
df=pd.read_csv("/Users/Vibhanshu/Desktop/MSc. Data Science/Python/Assignment/Sale_Customers.csv")
x=df["Annual Income (k$)"].mode()[0]
df["Annual Income (k$)"].fillna(x,inplace=True)
print(df.to_string())

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
7             8  Female   23                  18                      94
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
13           14  Female   24                  20                      77
14           15    Male   37                  20                      13
15           16    Male   22                  20                      79
16           17  Female   35                  21                      35
17           18    Male   20                  21                      66
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
21           22    Male   25                  24                      73
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
25           26    Male   29                  28                      82
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
29           30  Female   23                  29                      87
30           31    Male   60                  30                       4
31           32  Female   21                  30                      73
32           33    Male   53                  33                       4
33           34    Male   18                  33                      92
34           35  Female   49                  33                      14
35           36  Female   21                  33                      81
36           37  Female   42                  34                      17
37           38  Female   30                  34                      73
38           39  Female   36                  37                      26
39           40  Female   20                  37                      75
40           41  Female   65                  38                      35
41           42    Male   24                  38                      92
42           43    Male   48                  39                      36
43           44  Female   31                  39                      61
44           45  Female   49                  39                      28
45           46  Female   24                  39                      65
46           47  Female   50                  40                      55
47           48  Female   27                  40                      47
48           49  Female   29                  40                      42
49           50  Female   31                  40                      42
50           51  Female   49                  42                      52
51           52    Male   33                  42                      60
52           53  Female   31                  43                      54
53           54    Male   59                  43                      60
54           55  Female   50                  43                      45
55           56    Male   47                  43                      41
56           57  Female   51                  44                      50
57           58    Male   69                  44                      46
58           59  Female   27                  46                      51
59           60    Male   53                  46                      46
60           61    Male   70                  46                      56
61           62    Male   19                  46                      55
62           63  Female   67                  47                      52
63           64  Female   54                  47                      59
64           65    Male   63                  48                      51
65           66    Male   18                  48                      59
66           67  Female   43                  48                      50
67           68  Female   68                  48                      48
68           69    Male   19                  48                      59
69           70  Female   32                  48                      47
70           71    Male   70                  49                      55
71           72  Female   47                  49                      42
72           73  Female   60                  50                      49
73           74  Female   60                  50                      56
74           75    Male   59                  54                      47
75           76    Male   26                  54                      54
76           77  Female   45                  54                      53
77           78    Male   40                  54                      48
78           79  Female   23                  54                      52
79           80  Female   49                  54                      42
80           81    Male   57                  54                      51
81           82    Male   38                  54                      55
82           83    Male   67                  54                      41
83           84  Female   46                  54                      44
84           85  Female   21                  54                      57
85           86    Male   48                  54                      46
86           87  Female   55                  57                      58
87           88  Female   22                  57                      55
88           89  Female   34                  58                      60
89           90  Female   50                  58                      46
90           91  Female   68                  59                      55
91           92    Male   18                  59                      41
92           93    Male   48                  60                      49
93           94  Female   40                  60                      40
94           95  Female   32                  60                      42
95           96    Male   24                  60                      52
96           97  Female   47                  60                      47
97           98  Female   27                  60                      50
98           99    Male   48                  61                      42
99          100    Male   20                  61                      49
100         101  Female   23                  62                      41
101         102  Female   49                  62                      48
102         103    Male   67                  62                      59
103         104    Male   26                  62                      55
104         105    Male   49                  62                      56
105         106  Female   21                  62                      42
106         107  Female   66                  63                      50
107         108    Male   54                  63                      46
108         109    Male   68                  63                      43
109         110    Male   66                  63                      48
110         111    Male   65                  63                      52
111         112  Female   19                  63                      54
112         113  Female   38                  64                      42
113         114    Male   19                  64                      46
114         115  Female   18                  65                      48
115         116  Female   19                  65                      50
116         117  Female   63                  65                      43
117         118  Female   49                  65                      59
118         119  Female   51                  67                      43
119         120  Female   50                  67                      57
120         121    Male   27                  67                      56
121         122  Female   38                  67                      40
122         123  Female   40                  69                      58
123         124    Male   39                  69                      91
124         125  Female   23                  70                      29
125         126  Female   31                  70                      77
126         127    Male   43                  71                      35
127         128    Male   40                  71                      95
128         129    Male   59                  71                      11
129         130    Male   38                  71                      75
130         131    Male   47                  71                       9
131         132    Male   39                  71                      75
132         133  Female   25                  72                      34
133         134  Female   31                  72                      71
134         135    Male   20                  73                       5
135         136  Female   29                  73                      88
136         137  Female   44                  73                       7
137         138    Male   32                  73                      73
138         139    Male   19                  74                      10
139         140  Female   35                  74                      72
140         141  Female   57                  75                       5
141         142    Male   32                  75                      93
142         143  Female   28                  76                      40
143         144  Female   32                  76                      87
144         145    Male   25                  77                      12
145         146    Male   28                  77                      97
146         147    Male   48                  77                      36
147         148  Female   32                  77                      74
148         149  Female   34                  78                      22
149         150    Male   34                  78                      90
150         151    Male   43                  78                      17
151         152    Male   39                  78                      88
152         153  Female   44                  78                      20
153         154  Female   38                  78                      76
154         155  Female   47                  78                      16
155         156  Female   27                  78                      89
156         157    Male   37                  78                       1
157         158  Female   30                  78                      78
158         159    Male   34                  78                       1
159         160  Female   30                  78                      73
160         161  Female   56                  79                      35
161         162  Female   29                  79                      83
162         163    Male   19                  81                       5
163         164  Female   31                  81                      93
164         165    Male   50                  85                      26
165         166  Female   36                  85                      75
166         167    Male   42                  86                      20
167         168  Female   33                  86                      95
168         169  Female   36                  87                      27
169         170    Male   32                  87                      63
170         171    Male   40                  87                      13
171         172    Male   28                  87                      75
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
175         176  Female   30                  88                      86
176         177    Male   58                  88                      15
177         178    Male   27                  88                      69
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
183         184  Female   29                  98                      88
184         185  Female   41                  99                      39
185         186    Male   30                  99                      97
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [22]:
#Wrong Data
df=pd.read_csv("/Users/Vibhanshu/Desktop/MSc. Data Science/Python/Assignment/Sale_Customers.csv")
df.loc[7,"CustomerID "]=45
print(df.to_string())

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)  CustomerID
0             1    Male   19                  15                      39          NaN
1             2    Male   21                  15                      81          NaN
2             3  Female   20                  16                       6          NaN
3             4  Female   23                  16                      77          NaN
4             5  Female   31                  17                      40          NaN
5             6  Female   22                  17                      76          NaN
6             7  Female   35                  18                       6          NaN
7             8  Female   23                  18                      94         45.0
8             9    Male   64                  19                       3          NaN
9            10  Female   30                  19                      72          NaN
10           11    Male   67                  19                      14          NaN
11           12  Female   35                  19                      99          NaN
12           13  Female   58                  20                      15          NaN
13           14  Female   24                  20                      77          NaN
14           15    Male   37                  20                      13          NaN
15           16    Male   22                  20                      79          NaN
16           17  Female   35                  21                      35          NaN
17           18    Male   20                  21                      66          NaN
18           19    Male   52                  23                      29          NaN
19           20  Female   35                  23                      98          NaN
20           21    Male   35                  24                      35          NaN
21           22    Male   25                  24                      73          NaN
22           23  Female   46                  25                       5          NaN
23           24    Male   31                  25                      73          NaN
24           25  Female   54                  28                      14          NaN
25           26    Male   29                  28                      82          NaN
26           27  Female   45                  28                      32          NaN
27           28    Male   35                  28                      61          NaN
28           29  Female   40                  29                      31          NaN
29           30  Female   23                  29                      87          NaN
30           31    Male   60                  30                       4          NaN
31           32  Female   21                  30                      73          NaN
32           33    Male   53                  33                       4          NaN
33           34    Male   18                  33                      92          NaN
34           35  Female   49                  33                      14          NaN
35           36  Female   21                  33                      81          NaN
36           37  Female   42                  34                      17          NaN
37           38  Female   30                  34                      73          NaN
38           39  Female   36                  37                      26          NaN
39           40  Female   20                  37                      75          NaN
40           41  Female   65                  38                      35          NaN
41           42    Male   24                  38                      92          NaN
42           43    Male   48                  39                      36          NaN
43           44  Female   31                  39                      61          NaN
44           45  Female   49                  39                      28          NaN
45           46  Female   24                  39                      65          NaN
46           47  Female   50                  40                      55          NaN
47           48  Female   27                  40                      47          NaN
48           49  Female   29                  40                      42          NaN
49           50  Female   31                  40                      42          NaN
50           51  Female   49                  42                      52          NaN
51           52    Male   33                  42                      60          NaN
52           53  Female   31                  43                      54          NaN
53           54    Male   59                  43                      60          NaN
54           55  Female   50                  43                      45          NaN
55           56    Male   47                  43                      41          NaN
56           57  Female   51                  44                      50          NaN
57           58    Male   69                  44                      46          NaN
58           59  Female   27                  46                      51          NaN
59           60    Male   53                  46                      46          NaN
60           61    Male   70                  46                      56          NaN
61           62    Male   19                  46                      55          NaN
62           63  Female   67                  47                      52          NaN
63           64  Female   54                  47                      59          NaN
64           65    Male   63                  48                      51          NaN
65           66    Male   18                  48                      59          NaN
66           67  Female   43                  48                      50          NaN
67           68  Female   68                  48                      48          NaN
68           69    Male   19                  48                      59          NaN
69           70  Female   32                  48                      47          NaN
70           71    Male   70                  49                      55          NaN
71           72  Female   47                  49                      42          NaN
72           73  Female   60                  50                      49          NaN
73           74  Female   60                  50                      56          NaN
74           75    Male   59                  54                      47          NaN
75           76    Male   26                  54                      54          NaN
76           77  Female   45                  54                      53          NaN
77           78    Male   40                  54                      48          NaN
78           79  Female   23                  54                      52          NaN
79           80  Female   49                  54                      42          NaN
80           81    Male   57                  54                      51          NaN
81           82    Male   38                  54                      55          NaN
82           83    Male   67                  54                      41          NaN
83           84  Female   46                  54                      44          NaN
84           85  Female   21                  54                      57          NaN
85           86    Male   48                  54                      46          NaN
86           87  Female   55                  57                      58          NaN
87           88  Female   22                  57                      55          NaN
88           89  Female   34                  58                      60          NaN
89           90  Female   50                  58                      46          NaN
90           91  Female   68                  59                      55          NaN
91           92    Male   18                  59                      41          NaN
92           93    Male   48                  60                      49          NaN
93           94  Female   40                  60                      40          NaN
94           95  Female   32                  60                      42          NaN
95           96    Male   24                  60                      52          NaN
96           97  Female   47                  60                      47          NaN
97           98  Female   27                  60                      50          NaN
98           99    Male   48                  61                      42          NaN
99          100    Male   20                  61                      49          NaN
100         101  Female   23                  62                      41          NaN
101         102  Female   49                  62                      48          NaN
102         103    Male   67                  62                      59          NaN
103         104    Male   26                  62                      55          NaN
104         105    Male   49                  62                      56          NaN
105         106  Female   21                  62                      42          NaN
106         107  Female   66                  63                      50          NaN
107         108    Male   54                  63                      46          NaN
108         109    Male   68                  63                      43          NaN
109         110    Male   66                  63                      48          NaN
110         111    Male   65                  63                      52          NaN
111         112  Female   19                  63                      54          NaN
112         113  Female   38                  64                      42          NaN
113         114    Male   19                  64                      46          NaN
114         115  Female   18                  65                      48          NaN
115         116  Female   19                  65                      50          NaN
116         117  Female   63                  65                      43          NaN
117         118  Female   49                  65                      59          NaN
118         119  Female   51                  67                      43          NaN
119         120  Female   50                  67                      57          NaN
120         121    Male   27                  67                      56          NaN
121         122  Female   38                  67                      40          NaN
122         123  Female   40                  69                      58          NaN
123         124    Male   39                  69                      91          NaN
124         125  Female   23                  70                      29          NaN
125         126  Female   31                  70                      77          NaN
126         127    Male   43                  71                      35          NaN
127         128    Male   40                  71                      95          NaN
128         129    Male   59                  71                      11          NaN
129         130    Male   38                  71                      75          NaN
130         131    Male   47                  71                       9          NaN
131         132    Male   39                  71                      75          NaN
132         133  Female   25                  72                      34          NaN
133         134  Female   31                  72                      71          NaN
134         135    Male   20                  73                       5          NaN
135         136  Female   29                  73                      88          NaN
136         137  Female   44                  73                       7          NaN
137         138    Male   32                  73                      73          NaN
138         139    Male   19                  74                      10          NaN
139         140  Female   35                  74                      72          NaN
140         141  Female   57                  75                       5          NaN
141         142    Male   32                  75                      93          NaN
142         143  Female   28                  76                      40          NaN
143         144  Female   32                  76                      87          NaN
144         145    Male   25                  77                      12          NaN
145         146    Male   28                  77                      97          NaN
146         147    Male   48                  77                      36          NaN
147         148  Female   32                  77                      74          NaN
148         149  Female   34                  78                      22          NaN
149         150    Male   34                  78                      90          NaN
150         151    Male   43                  78                      17          NaN
151         152    Male   39                  78                      88          NaN
152         153  Female   44                  78                      20          NaN
153         154  Female   38                  78                      76          NaN
154         155  Female   47                  78                      16          NaN
155         156  Female   27                  78                      89          NaN
156         157    Male   37                  78                       1          NaN
157         158  Female   30                  78                      78          NaN
158         159    Male   34                  78                       1          NaN
159         160  Female   30                  78                      73          NaN
160         161  Female   56                  79                      35          NaN
161         162  Female   29                  79                      83          NaN
162         163    Male   19                  81                       5          NaN
163         164  Female   31                  81                      93          NaN
164         165    Male   50                  85                      26          NaN
165         166  Female   36                  85                      75          NaN
166         167    Male   42                  86                      20          NaN
167         168  Female   33                  86                      95          NaN
168         169  Female   36                  87                      27          NaN
169         170    Male   32                  87                      63          NaN
170         171    Male   40                  87                      13          NaN
171         172    Male   28                  87                      75          NaN
172         173    Male   36                  87                      10          NaN
173         174    Male   36                  87                      92          NaN
174         175  Female   52                  88                      13          NaN
175         176  Female   30                  88                      86          NaN
176         177    Male   58                  88                      15          NaN
177         178    Male   27                  88                      69          NaN
178         179    Male   59                  93                      14          NaN
179         180    Male   35                  93                      90          NaN
180         181  Female   37                  97                      32          NaN
181         182  Female   32                  97                      86          NaN
182         183    Male   46                  98                      15          NaN
183         184  Female   29                  98                      88          NaN
184         185  Female   41                  99                      39          NaN
185         186    Male   30                  99                      97          NaN
186         187  Female   54                 101                      24          NaN
187         188    Male   28                 101                      68          NaN
188         189  Female   41                 103                      17          NaN
189         190  Female   36                 103                      85          NaN
190         191  Female   34                 103                      23          NaN
191         192  Female   32                 103                      69          NaN
192         193    Male   33                 113                       8          NaN
193         194  Female   38                 113                      91          NaN
194         195  Female   47                 120                      16          NaN
195         196  Female   35                 120                      79          NaN
196         197  Female   45                 126                      28          NaN
197         198    Male   32                 126                      74          NaN
198         199    Male   32                 137                      18          NaN
199         200    Male   30                 137                      83          NaN

In [23]:
for x in df.index:
    if df.loc[x,"CustomerID "]>120:
        df.loc[x,"CustomerID "]=120
print(df.to_string())

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)  CustomerID
0             1    Male   19                  15                      39          NaN
1             2    Male   21                  15                      81          NaN
2             3  Female   20                  16                       6          NaN
3             4  Female   23                  16                      77          NaN
4             5  Female   31                  17                      40          NaN
5             6  Female   22                  17                      76          NaN
6             7  Female   35                  18                       6          NaN
7             8  Female   23                  18                      94         45.0
8             9    Male   64                  19                       3          NaN
9            10  Female   30                  19                      72          NaN
10           11    Male   67                  19                      14          NaN
11           12  Female   35                  19                      99          NaN
12           13  Female   58                  20                      15          NaN
13           14  Female   24                  20                      77          NaN
14           15    Male   37                  20                      13          NaN
15           16    Male   22                  20                      79          NaN
16           17  Female   35                  21                      35          NaN
17           18    Male   20                  21                      66          NaN
18           19    Male   52                  23                      29          NaN
19           20  Female   35                  23                      98          NaN
20           21    Male   35                  24                      35          NaN
21           22    Male   25                  24                      73          NaN
22           23  Female   46                  25                       5          NaN
23           24    Male   31                  25                      73          NaN
24           25  Female   54                  28                      14          NaN
25           26    Male   29                  28                      82          NaN
26           27  Female   45                  28                      32          NaN
27           28    Male   35                  28                      61          NaN
28           29  Female   40                  29                      31          NaN
29           30  Female   23                  29                      87          NaN
30           31    Male   60                  30                       4          NaN
31           32  Female   21                  30                      73          NaN
32           33    Male   53                  33                       4          NaN
33           34    Male   18                  33                      92          NaN
34           35  Female   49                  33                      14          NaN
35           36  Female   21                  33                      81          NaN
36           37  Female   42                  34                      17          NaN
37           38  Female   30                  34                      73          NaN
38           39  Female   36                  37                      26          NaN
39           40  Female   20                  37                      75          NaN
40           41  Female   65                  38                      35          NaN
41           42    Male   24                  38                      92          NaN
42           43    Male   48                  39                      36          NaN
43           44  Female   31                  39                      61          NaN
44           45  Female   49                  39                      28          NaN
45           46  Female   24                  39                      65          NaN
46           47  Female   50                  40                      55          NaN
47           48  Female   27                  40                      47          NaN
48           49  Female   29                  40                      42          NaN
49           50  Female   31                  40                      42          NaN
50           51  Female   49                  42                      52          NaN
51           52    Male   33                  42                      60          NaN
52           53  Female   31                  43                      54          NaN
53           54    Male   59                  43                      60          NaN
54           55  Female   50                  43                      45          NaN
55           56    Male   47                  43                      41          NaN
56           57  Female   51                  44                      50          NaN
57           58    Male   69                  44                      46          NaN
58           59  Female   27                  46                      51          NaN
59           60    Male   53                  46                      46          NaN
60           61    Male   70                  46                      56          NaN
61           62    Male   19                  46                      55          NaN
62           63  Female   67                  47                      52          NaN
63           64  Female   54                  47                      59          NaN
64           65    Male   63                  48                      51          NaN
65           66    Male   18                  48                      59          NaN
66           67  Female   43                  48                      50          NaN
67           68  Female   68                  48                      48          NaN
68           69    Male   19                  48                      59          NaN
69           70  Female   32                  48                      47          NaN
70           71    Male   70                  49                      55          NaN
71           72  Female   47                  49                      42          NaN
72           73  Female   60                  50                      49          NaN
73           74  Female   60                  50                      56          NaN
74           75    Male   59                  54                      47          NaN
75           76    Male   26                  54                      54          NaN
76           77  Female   45                  54                      53          NaN
77           78    Male   40                  54                      48          NaN
78           79  Female   23                  54                      52          NaN
79           80  Female   49                  54                      42          NaN
80           81    Male   57                  54                      51          NaN
81           82    Male   38                  54                      55          NaN
82           83    Male   67                  54                      41          NaN
83           84  Female   46                  54                      44          NaN
84           85  Female   21                  54                      57          NaN
85           86    Male   48                  54                      46          NaN
86           87  Female   55                  57                      58          NaN
87           88  Female   22                  57                      55          NaN
88           89  Female   34                  58                      60          NaN
89           90  Female   50                  58                      46          NaN
90           91  Female   68                  59                      55          NaN
91           92    Male   18                  59                      41          NaN
92           93    Male   48                  60                      49          NaN
93           94  Female   40                  60                      40          NaN
94           95  Female   32                  60                      42          NaN
95           96    Male   24                  60                      52          NaN
96           97  Female   47                  60                      47          NaN
97           98  Female   27                  60                      50          NaN
98           99    Male   48                  61                      42          NaN
99          100    Male   20                  61                      49          NaN
100         101  Female   23                  62                      41          NaN
101         102  Female   49                  62                      48          NaN
102         103    Male   67                  62                      59          NaN
103         104    Male   26                  62                      55          NaN
104         105    Male   49                  62                      56          NaN
105         106  Female   21                  62                      42          NaN
106         107  Female   66                  63                      50          NaN
107         108    Male   54                  63                      46          NaN
108         109    Male   68                  63                      43          NaN
109         110    Male   66                  63                      48          NaN
110         111    Male   65                  63                      52          NaN
111         112  Female   19                  63                      54          NaN
112         113  Female   38                  64                      42          NaN
113         114    Male   19                  64                      46          NaN
114         115  Female   18                  65                      48          NaN
115         116  Female   19                  65                      50          NaN
116         117  Female   63                  65                      43          NaN
117         118  Female   49                  65                      59          NaN
118         119  Female   51                  67                      43          NaN
119         120  Female   50                  67                      57          NaN
120         121    Male   27                  67                      56          NaN
121         122  Female   38                  67                      40          NaN
122         123  Female   40                  69                      58          NaN
123         124    Male   39                  69                      91          NaN
124         125  Female   23                  70                      29          NaN
125         126  Female   31                  70                      77          NaN
126         127    Male   43                  71                      35          NaN
127         128    Male   40                  71                      95          NaN
128         129    Male   59                  71                      11          NaN
129         130    Male   38                  71                      75          NaN
130         131    Male   47                  71                       9          NaN
131         132    Male   39                  71                      75          NaN
132         133  Female   25                  72                      34          NaN
133         134  Female   31                  72                      71          NaN
134         135    Male   20                  73                       5          NaN
135         136  Female   29                  73                      88          NaN
136         137  Female   44                  73                       7          NaN
137         138    Male   32                  73                      73          NaN
138         139    Male   19                  74                      10          NaN
139         140  Female   35                  74                      72          NaN
140         141  Female   57                  75                       5          NaN
141         142    Male   32                  75                      93          NaN
142         143  Female   28                  76                      40          NaN
143         144  Female   32                  76                      87          NaN
144         145    Male   25                  77                      12          NaN
145         146    Male   28                  77                      97          NaN
146         147    Male   48                  77                      36          NaN
147         148  Female   32                  77                      74          NaN
148         149  Female   34                  78                      22          NaN
149         150    Male   34                  78                      90          NaN
150         151    Male   43                  78                      17          NaN
151         152    Male   39                  78                      88          NaN
152         153  Female   44                  78                      20          NaN
153         154  Female   38                  78                      76          NaN
154         155  Female   47                  78                      16          NaN
155         156  Female   27                  78                      89          NaN
156         157    Male   37                  78                       1          NaN
157         158  Female   30                  78                      78          NaN
158         159    Male   34                  78                       1          NaN
159         160  Female   30                  78                      73          NaN
160         161  Female   56                  79                      35          NaN
161         162  Female   29                  79                      83          NaN
162         163    Male   19                  81                       5          NaN
163         164  Female   31                  81                      93          NaN
164         165    Male   50                  85                      26          NaN
165         166  Female   36                  85                      75          NaN
166         167    Male   42                  86                      20          NaN
167         168  Female   33                  86                      95          NaN
168         169  Female   36                  87                      27          NaN
169         170    Male   32                  87                      63          NaN
170         171    Male   40                  87                      13          NaN
171         172    Male   28                  87                      75          NaN
172         173    Male   36                  87                      10          NaN
173         174    Male   36                  87                      92          NaN
174         175  Female   52                  88                      13          NaN
175         176  Female   30                  88                      86          NaN
176         177    Male   58                  88                      15          NaN
177         178    Male   27                  88                      69          NaN
178         179    Male   59                  93                      14          NaN
179         180    Male   35                  93                      90          NaN
180         181  Female   37                  97                      32          NaN
181         182  Female   32                  97                      86          NaN
182         183    Male   46                  98                      15          NaN
183         184  Female   29                  98                      88          NaN
184         185  Female   41                  99                      39          NaN
185         186    Male   30                  99                      97          NaN
186         187  Female   54                 101                      24          NaN
187         188    Male   28                 101                      68          NaN
188         189  Female   41                 103                      17          NaN
189         190  Female   36                 103                      85          NaN
190         191  Female   34                 103                      23          NaN
191         192  Female   32                 103                      69          NaN
192         193    Male   33                 113                       8          NaN
193         194  Female   38                 113                      91          NaN
194         195  Female   47                 120                      16          NaN
195         196  Female   35                 120                      79          NaN
196         197  Female   45                 126                      28          NaN
197         198    Male   32                 126                      74          NaN
198         199    Male   32                 137                      18          NaN
199         200    Male   30                 137                      83          NaN

In [24]:
for x in df.index:
    if df.loc[x,"CustomerID "]>120:
        df.drop(x,inplace=True)
print(df.to_string())

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)  CustomerID
0             1    Male   19                  15                      39          NaN
1             2    Male   21                  15                      81          NaN
2             3  Female   20                  16                       6          NaN
3             4  Female   23                  16                      77          NaN
4             5  Female   31                  17                      40          NaN
5             6  Female   22                  17                      76          NaN
6             7  Female   35                  18                       6          NaN
7             8  Female   23                  18                      94         45.0
8             9    Male   64                  19                       3          NaN
9            10  Female   30                  19                      72          NaN
10           11    Male   67                  19                      14          NaN
11           12  Female   35                  19                      99          NaN
12           13  Female   58                  20                      15          NaN
13           14  Female   24                  20                      77          NaN
14           15    Male   37                  20                      13          NaN
15           16    Male   22                  20                      79          NaN
16           17  Female   35                  21                      35          NaN
17           18    Male   20                  21                      66          NaN
18           19    Male   52                  23                      29          NaN
19           20  Female   35                  23                      98          NaN
20           21    Male   35                  24                      35          NaN
21           22    Male   25                  24                      73          NaN
22           23  Female   46                  25                       5          NaN
23           24    Male   31                  25                      73          NaN
24           25  Female   54                  28                      14          NaN
25           26    Male   29                  28                      82          NaN
26           27  Female   45                  28                      32          NaN
27           28    Male   35                  28                      61          NaN
28           29  Female   40                  29                      31          NaN
29           30  Female   23                  29                      87          NaN
30           31    Male   60                  30                       4          NaN
31           32  Female   21                  30                      73          NaN
32           33    Male   53                  33                       4          NaN
33           34    Male   18                  33                      92          NaN
34           35  Female   49                  33                      14          NaN
35           36  Female   21                  33                      81          NaN
36           37  Female   42                  34                      17          NaN
37           38  Female   30                  34                      73          NaN
38           39  Female   36                  37                      26          NaN
39           40  Female   20                  37                      75          NaN
40           41  Female   65                  38                      35          NaN
41           42    Male   24                  38                      92          NaN
42           43    Male   48                  39                      36          NaN
43           44  Female   31                  39                      61          NaN
44           45  Female   49                  39                      28          NaN
45           46  Female   24                  39                      65          NaN
46           47  Female   50                  40                      55          NaN
47           48  Female   27                  40                      47          NaN
48           49  Female   29                  40                      42          NaN
49           50  Female   31                  40                      42          NaN
50           51  Female   49                  42                      52          NaN
51           52    Male   33                  42                      60          NaN
52           53  Female   31                  43                      54          NaN
53           54    Male   59                  43                      60          NaN
54           55  Female   50                  43                      45          NaN
55           56    Male   47                  43                      41          NaN
56           57  Female   51                  44                      50          NaN
57           58    Male   69                  44                      46          NaN
58           59  Female   27                  46                      51          NaN
59           60    Male   53                  46                      46          NaN
60           61    Male   70                  46                      56          NaN
61           62    Male   19                  46                      55          NaN
62           63  Female   67                  47                      52          NaN
63           64  Female   54                  47                      59          NaN
64           65    Male   63                  48                      51          NaN
65           66    Male   18                  48                      59          NaN
66           67  Female   43                  48                      50          NaN
67           68  Female   68                  48                      48          NaN
68           69    Male   19                  48                      59          NaN
69           70  Female   32                  48                      47          NaN
70           71    Male   70                  49                      55          NaN
71           72  Female   47                  49                      42          NaN
72           73  Female   60                  50                      49          NaN
73           74  Female   60                  50                      56          NaN
74           75    Male   59                  54                      47          NaN
75           76    Male   26                  54                      54          NaN
76           77  Female   45                  54                      53          NaN
77           78    Male   40                  54                      48          NaN
78           79  Female   23                  54                      52          NaN
79           80  Female   49                  54                      42          NaN
80           81    Male   57                  54                      51          NaN
81           82    Male   38                  54                      55          NaN
82           83    Male   67                  54                      41          NaN
83           84  Female   46                  54                      44          NaN
84           85  Female   21                  54                      57          NaN
85           86    Male   48                  54                      46          NaN
86           87  Female   55                  57                      58          NaN
87           88  Female   22                  57                      55          NaN
88           89  Female   34                  58                      60          NaN
89           90  Female   50                  58                      46          NaN
90           91  Female   68                  59                      55          NaN
91           92    Male   18                  59                      41          NaN
92           93    Male   48                  60                      49          NaN
93           94  Female   40                  60                      40          NaN
94           95  Female   32                  60                      42          NaN
95           96    Male   24                  60                      52          NaN
96           97  Female   47                  60                      47          NaN
97           98  Female   27                  60                      50          NaN
98           99    Male   48                  61                      42          NaN
99          100    Male   20                  61                      49          NaN
100         101  Female   23                  62                      41          NaN
101         102  Female   49                  62                      48          NaN
102         103    Male   67                  62                      59          NaN
103         104    Male   26                  62                      55          NaN
104         105    Male   49                  62                      56          NaN
105         106  Female   21                  62                      42          NaN
106         107  Female   66                  63                      50          NaN
107         108    Male   54                  63                      46          NaN
108         109    Male   68                  63                      43          NaN
109         110    Male   66                  63                      48          NaN
110         111    Male   65                  63                      52          NaN
111         112  Female   19                  63                      54          NaN
112         113  Female   38                  64                      42          NaN
113         114    Male   19                  64                      46          NaN
114         115  Female   18                  65                      48          NaN
115         116  Female   19                  65                      50          NaN
116         117  Female   63                  65                      43          NaN
117         118  Female   49                  65                      59          NaN
118         119  Female   51                  67                      43          NaN
119         120  Female   50                  67                      57          NaN
120         121    Male   27                  67                      56          NaN
121         122  Female   38                  67                      40          NaN
122         123  Female   40                  69                      58          NaN
123         124    Male   39                  69                      91          NaN
124         125  Female   23                  70                      29          NaN
125         126  Female   31                  70                      77          NaN
126         127    Male   43                  71                      35          NaN
127         128    Male   40                  71                      95          NaN
128         129    Male   59                  71                      11          NaN
129         130    Male   38                  71                      75          NaN
130         131    Male   47                  71                       9          NaN
131         132    Male   39                  71                      75          NaN
132         133  Female   25                  72                      34          NaN
133         134  Female   31                  72                      71          NaN
134         135    Male   20                  73                       5          NaN
135         136  Female   29                  73                      88          NaN
136         137  Female   44                  73                       7          NaN
137         138    Male   32                  73                      73          NaN
138         139    Male   19                  74                      10          NaN
139         140  Female   35                  74                      72          NaN
140         141  Female   57                  75                       5          NaN
141         142    Male   32                  75                      93          NaN
142         143  Female   28                  76                      40          NaN
143         144  Female   32                  76                      87          NaN
144         145    Male   25                  77                      12          NaN
145         146    Male   28                  77                      97          NaN
146         147    Male   48                  77                      36          NaN
147         148  Female   32                  77                      74          NaN
148         149  Female   34                  78                      22          NaN
149         150    Male   34                  78                      90          NaN
150         151    Male   43                  78                      17          NaN
151         152    Male   39                  78                      88          NaN
152         153  Female   44                  78                      20          NaN
153         154  Female   38                  78                      76          NaN
154         155  Female   47                  78                      16          NaN
155         156  Female   27                  78                      89          NaN
156         157    Male   37                  78                       1          NaN
157         158  Female   30                  78                      78          NaN
158         159    Male   34                  78                       1          NaN
159         160  Female   30                  78                      73          NaN
160         161  Female   56                  79                      35          NaN
161         162  Female   29                  79                      83          NaN
162         163    Male   19                  81                       5          NaN
163         164  Female   31                  81                      93          NaN
164         165    Male   50                  85                      26          NaN
165         166  Female   36                  85                      75          NaN
166         167    Male   42                  86                      20          NaN
167         168  Female   33                  86                      95          NaN
168         169  Female   36                  87                      27          NaN
169         170    Male   32                  87                      63          NaN
170         171    Male   40                  87                      13          NaN
171         172    Male   28                  87                      75          NaN
172         173    Male   36                  87                      10          NaN
173         174    Male   36                  87                      92          NaN
174         175  Female   52                  88                      13          NaN
175         176  Female   30                  88                      86          NaN
176         177    Male   58                  88                      15          NaN
177         178    Male   27                  88                      69          NaN
178         179    Male   59                  93                      14          NaN
179         180    Male   35                  93                      90          NaN
180         181  Female   37                  97                      32          NaN
181         182  Female   32                  97                      86          NaN
182         183    Male   46                  98                      15          NaN
183         184  Female   29                  98                      88          NaN
184         185  Female   41                  99                      39          NaN
185         186    Male   30                  99                      97          NaN
186         187  Female   54                 101                      24          NaN
187         188    Male   28                 101                      68          NaN
188         189  Female   41                 103                      17          NaN
189         190  Female   36                 103                      85          NaN
190         191  Female   34                 103                      23          NaN
191         192  Female   32                 103                      69          NaN
192         193    Male   33                 113                       8          NaN
193         194  Female   38                 113                      91          NaN
194         195  Female   47                 120                      16          NaN
195         196  Female   35                 120                      79          NaN
196         197  Female   45                 126                      28          NaN
197         198    Male   32                 126                      74          NaN
198         199    Male   32                 137                      18          NaN
199         200    Male   30                 137                      83          NaN

In [25]:
#Removing Duplicates
df=pd.read_csv("/Users/Vibhanshu/Desktop/MSc. Data Science/Python/Assignment/Sale_Customers.csv")
print(df.to_string())

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
7             8  Female   23                  18                      94
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
13           14  Female   24                  20                      77
14           15    Male   37                  20                      13
15           16    Male   22                  20                      79
16           17  Female   35                  21                      35
17           18    Male   20                  21                      66
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
21           22    Male   25                  24                      73
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
25           26    Male   29                  28                      82
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
29           30  Female   23                  29                      87
30           31    Male   60                  30                       4
31           32  Female   21                  30                      73
32           33    Male   53                  33                       4
33           34    Male   18                  33                      92
34           35  Female   49                  33                      14
35           36  Female   21                  33                      81
36           37  Female   42                  34                      17
37           38  Female   30                  34                      73
38           39  Female   36                  37                      26
39           40  Female   20                  37                      75
40           41  Female   65                  38                      35
41           42    Male   24                  38                      92
42           43    Male   48                  39                      36
43           44  Female   31                  39                      61
44           45  Female   49                  39                      28
45           46  Female   24                  39                      65
46           47  Female   50                  40                      55
47           48  Female   27                  40                      47
48           49  Female   29                  40                      42
49           50  Female   31                  40                      42
50           51  Female   49                  42                      52
51           52    Male   33                  42                      60
52           53  Female   31                  43                      54
53           54    Male   59                  43                      60
54           55  Female   50                  43                      45
55           56    Male   47                  43                      41
56           57  Female   51                  44                      50
57           58    Male   69                  44                      46
58           59  Female   27                  46                      51
59           60    Male   53                  46                      46
60           61    Male   70                  46                      56
61           62    Male   19                  46                      55
62           63  Female   67                  47                      52
63           64  Female   54                  47                      59
64           65    Male   63                  48                      51
65           66    Male   18                  48                      59
66           67  Female   43                  48                      50
67           68  Female   68                  48                      48
68           69    Male   19                  48                      59
69           70  Female   32                  48                      47
70           71    Male   70                  49                      55
71           72  Female   47                  49                      42
72           73  Female   60                  50                      49
73           74  Female   60                  50                      56
74           75    Male   59                  54                      47
75           76    Male   26                  54                      54
76           77  Female   45                  54                      53
77           78    Male   40                  54                      48
78           79  Female   23                  54                      52
79           80  Female   49                  54                      42
80           81    Male   57                  54                      51
81           82    Male   38                  54                      55
82           83    Male   67                  54                      41
83           84  Female   46                  54                      44
84           85  Female   21                  54                      57
85           86    Male   48                  54                      46
86           87  Female   55                  57                      58
87           88  Female   22                  57                      55
88           89  Female   34                  58                      60
89           90  Female   50                  58                      46
90           91  Female   68                  59                      55
91           92    Male   18                  59                      41
92           93    Male   48                  60                      49
93           94  Female   40                  60                      40
94           95  Female   32                  60                      42
95           96    Male   24                  60                      52
96           97  Female   47                  60                      47
97           98  Female   27                  60                      50
98           99    Male   48                  61                      42
99          100    Male   20                  61                      49
100         101  Female   23                  62                      41
101         102  Female   49                  62                      48
102         103    Male   67                  62                      59
103         104    Male   26                  62                      55
104         105    Male   49                  62                      56
105         106  Female   21                  62                      42
106         107  Female   66                  63                      50
107         108    Male   54                  63                      46
108         109    Male   68                  63                      43
109         110    Male   66                  63                      48
110         111    Male   65                  63                      52
111         112  Female   19                  63                      54
112         113  Female   38                  64                      42
113         114    Male   19                  64                      46
114         115  Female   18                  65                      48
115         116  Female   19                  65                      50
116         117  Female   63                  65                      43
117         118  Female   49                  65                      59
118         119  Female   51                  67                      43
119         120  Female   50                  67                      57
120         121    Male   27                  67                      56
121         122  Female   38                  67                      40
122         123  Female   40                  69                      58
123         124    Male   39                  69                      91
124         125  Female   23                  70                      29
125         126  Female   31                  70                      77
126         127    Male   43                  71                      35
127         128    Male   40                  71                      95
128         129    Male   59                  71                      11
129         130    Male   38                  71                      75
130         131    Male   47                  71                       9
131         132    Male   39                  71                      75
132         133  Female   25                  72                      34
133         134  Female   31                  72                      71
134         135    Male   20                  73                       5
135         136  Female   29                  73                      88
136         137  Female   44                  73                       7
137         138    Male   32                  73                      73
138         139    Male   19                  74                      10
139         140  Female   35                  74                      72
140         141  Female   57                  75                       5
141         142    Male   32                  75                      93
142         143  Female   28                  76                      40
143         144  Female   32                  76                      87
144         145    Male   25                  77                      12
145         146    Male   28                  77                      97
146         147    Male   48                  77                      36
147         148  Female   32                  77                      74
148         149  Female   34                  78                      22
149         150    Male   34                  78                      90
150         151    Male   43                  78                      17
151         152    Male   39                  78                      88
152         153  Female   44                  78                      20
153         154  Female   38                  78                      76
154         155  Female   47                  78                      16
155         156  Female   27                  78                      89
156         157    Male   37                  78                       1
157         158  Female   30                  78                      78
158         159    Male   34                  78                       1
159         160  Female   30                  78                      73
160         161  Female   56                  79                      35
161         162  Female   29                  79                      83
162         163    Male   19                  81                       5
163         164  Female   31                  81                      93
164         165    Male   50                  85                      26
165         166  Female   36                  85                      75
166         167    Male   42                  86                      20
167         168  Female   33                  86                      95
168         169  Female   36                  87                      27
169         170    Male   32                  87                      63
170         171    Male   40                  87                      13
171         172    Male   28                  87                      75
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
175         176  Female   30                  88                      86
176         177    Male   58                  88                      15
177         178    Male   27                  88                      69
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
183         184  Female   29                  98                      88
184         185  Female   41                  99                      39
185         186    Male   30                  99                      97
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [26]:
df.drop_duplicates(inplace=True)
print(df.to_string())

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
7             8  Female   23                  18                      94
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
13           14  Female   24                  20                      77
14           15    Male   37                  20                      13
15           16    Male   22                  20                      79
16           17  Female   35                  21                      35
17           18    Male   20                  21                      66
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
21           22    Male   25                  24                      73
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
25           26    Male   29                  28                      82
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
29           30  Female   23                  29                      87
30           31    Male   60                  30                       4
31           32  Female   21                  30                      73
32           33    Male   53                  33                       4
33           34    Male   18                  33                      92
34           35  Female   49                  33                      14
35           36  Female   21                  33                      81
36           37  Female   42                  34                      17
37           38  Female   30                  34                      73
38           39  Female   36                  37                      26
39           40  Female   20                  37                      75
40           41  Female   65                  38                      35
41           42    Male   24                  38                      92
42           43    Male   48                  39                      36
43           44  Female   31                  39                      61
44           45  Female   49                  39                      28
45           46  Female   24                  39                      65
46           47  Female   50                  40                      55
47           48  Female   27                  40                      47
48           49  Female   29                  40                      42
49           50  Female   31                  40                      42
50           51  Female   49                  42                      52
51           52    Male   33                  42                      60
52           53  Female   31                  43                      54
53           54    Male   59                  43                      60
54           55  Female   50                  43                      45
55           56    Male   47                  43                      41
56           57  Female   51                  44                      50
57           58    Male   69                  44                      46
58           59  Female   27                  46                      51
59           60    Male   53                  46                      46
60           61    Male   70                  46                      56
61           62    Male   19                  46                      55
62           63  Female   67                  47                      52
63           64  Female   54                  47                      59
64           65    Male   63                  48                      51
65           66    Male   18                  48                      59
66           67  Female   43                  48                      50
67           68  Female   68                  48                      48
68           69    Male   19                  48                      59
69           70  Female   32                  48                      47
70           71    Male   70                  49                      55
71           72  Female   47                  49                      42
72           73  Female   60                  50                      49
73           74  Female   60                  50                      56
74           75    Male   59                  54                      47
75           76    Male   26                  54                      54
76           77  Female   45                  54                      53
77           78    Male   40                  54                      48
78           79  Female   23                  54                      52
79           80  Female   49                  54                      42
80           81    Male   57                  54                      51
81           82    Male   38                  54                      55
82           83    Male   67                  54                      41
83           84  Female   46                  54                      44
84           85  Female   21                  54                      57
85           86    Male   48                  54                      46
86           87  Female   55                  57                      58
87           88  Female   22                  57                      55
88           89  Female   34                  58                      60
89           90  Female   50                  58                      46
90           91  Female   68                  59                      55
91           92    Male   18                  59                      41
92           93    Male   48                  60                      49
93           94  Female   40                  60                      40
94           95  Female   32                  60                      42
95           96    Male   24                  60                      52
96           97  Female   47                  60                      47
97           98  Female   27                  60                      50
98           99    Male   48                  61                      42
99          100    Male   20                  61                      49
100         101  Female   23                  62                      41
101         102  Female   49                  62                      48
102         103    Male   67                  62                      59
103         104    Male   26                  62                      55
104         105    Male   49                  62                      56
105         106  Female   21                  62                      42
106         107  Female   66                  63                      50
107         108    Male   54                  63                      46
108         109    Male   68                  63                      43
109         110    Male   66                  63                      48
110         111    Male   65                  63                      52
111         112  Female   19                  63                      54
112         113  Female   38                  64                      42
113         114    Male   19                  64                      46
114         115  Female   18                  65                      48
115         116  Female   19                  65                      50
116         117  Female   63                  65                      43
117         118  Female   49                  65                      59
118         119  Female   51                  67                      43
119         120  Female   50                  67                      57
120         121    Male   27                  67                      56
121         122  Female   38                  67                      40
122         123  Female   40                  69                      58
123         124    Male   39                  69                      91
124         125  Female   23                  70                      29
125         126  Female   31                  70                      77
126         127    Male   43                  71                      35
127         128    Male   40                  71                      95
128         129    Male   59                  71                      11
129         130    Male   38                  71                      75
130         131    Male   47                  71                       9
131         132    Male   39                  71                      75
132         133  Female   25                  72                      34
133         134  Female   31                  72                      71
134         135    Male   20                  73                       5
135         136  Female   29                  73                      88
136         137  Female   44                  73                       7
137         138    Male   32                  73                      73
138         139    Male   19                  74                      10
139         140  Female   35                  74                      72
140         141  Female   57                  75                       5
141         142    Male   32                  75                      93
142         143  Female   28                  76                      40
143         144  Female   32                  76                      87
144         145    Male   25                  77                      12
145         146    Male   28                  77                      97
146         147    Male   48                  77                      36
147         148  Female   32                  77                      74
148         149  Female   34                  78                      22
149         150    Male   34                  78                      90
150         151    Male   43                  78                      17
151         152    Male   39                  78                      88
152         153  Female   44                  78                      20
153         154  Female   38                  78                      76
154         155  Female   47                  78                      16
155         156  Female   27                  78                      89
156         157    Male   37                  78                       1
157         158  Female   30                  78                      78
158         159    Male   34                  78                       1
159         160  Female   30                  78                      73
160         161  Female   56                  79                      35
161         162  Female   29                  79                      83
162         163    Male   19                  81                       5
163         164  Female   31                  81                      93
164         165    Male   50                  85                      26
165         166  Female   36                  85                      75
166         167    Male   42                  86                      20
167         168  Female   33                  86                      95
168         169  Female   36                  87                      27
169         170    Male   32                  87                      63
170         171    Male   40                  87                      13
171         172    Male   28                  87                      75
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
175         176  Female   30                  88                      86
176         177    Male   58                  88                      15
177         178    Male   27                  88                      69
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
183         184  Female   29                  98                      88
184         185  Female   41                  99                      39
185         186    Male   30                  99                      97
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [27]:
#Corelation
#corr() calculates the relationship b/w each column in the data set.
#The number varies from -1 to 1.
df=pd.read_csv("/Users/Vibhanshu/Desktop/MSc. Data Science/Python/Assignment/Sale_Customers.csv")
df.corr()

/var/folders/sp/2q6vh_9j0w1cb0bdct78zbm40000gn/T/ipykernel_4638/1836985535.py:5: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,CustomerID,Age,Annual Income (k$),Spending Score (1-100)
CustomerID,1.000000,-0.026763,0.977548,0.013835
Age,-0.026763,1.000000,-0.012398,-0.327227
Annual Income (k$),0.977548,-0.012398,1.000000,0.009903
Spending Score (1-100),0.013835,-0.327227,0.009903,1.000000